set(LLEA_SRCS
    src/assertions.f90
    src/bodies.f90
    src/constants.f90
    src/containers.f90
    src/dopri.f90
    src/ephemerides.f90
    src/epochs.f90
    src/events.f90
    src/exceptions.f90
    src/forces.f90
    src/integrators.f90
    src/interfaces.f90
    src/llea.f90
    src/math.f90
    src/naif.f90
    src/propagators.f90
    src/rotations.f90
    src/splines.f90
    src/states.f90
    src/trajectories.f90
    src/types.f90
    src/util.f90)
