set(CMAKE_Fortran_MODULE_DIRECTORY ${CMAKE_BINARY_DIR}/include)

if(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
    set(f90flags  "-cpp -fbacktrace -ffree-line-length-none")
    if(WIN32)
        set(f90flags  "${f90flags} -D_WIN32")
    else()
        set(f90flags  "${f90flags} -D_unix_")
    endif()
    set(CMAKE_Fortran_FLAGS_DEBUG "-g -Og -Wall -Wextra -pedantic -fcheck=all -ffpe-trap=invalid,overflow,underflow,zero ${f90flags}")
    set(CMAKE_Fortran_FLAGS_RELEASE "-fopenmp -O3 ${f90flags}")
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
	if(WIN32)
		set(f90flags  "/fpp /assume:realloc_lhs /traceback /nogen-interfaces")
		set(CMAKE_Fortran_FLAGS_RELEASE "/O3 /Qopenmp ${f90flags}")
		set(CMAKE_Fortran_FLAGS_DEBUG "/debug:full /Od /warn /check:all /Qtrapuv /fpe:3 ${f90flags}")
	else()
		set(f90flags  "-fpp -assume realloc_lhs -traceback -nogen-interfaces")
		set(CMAKE_Fortran_FLAGS_RELEASE "-openmp -O3 ${f90flags}")
        set(CMAKE_Fortran_FLAGS_DEBUG "-g -O0 -debug all -warn -ftrapuv -fp-stack-check -check all -fpe3 ${f90flags}")
    endif()
endif()
